In [1]:
# Performed with reference from online content of Simplilearn

In [2]:
# Experimental drug was tested on 2100 individuals between 13 to 100 years of Age.Half the participants are under 65 and around 95% of the participants under 65 experienced no side effects.95% of participants over 65 experienced side effects.

In [3]:
# Building a model to determine if a person suffered from side effect or not

In [4]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [5]:
train_labels=[]
train_samples=[]

In [6]:
# 5% of younger individuals who experienced side effects
for i in range(50):
  random_younger=randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(1)

# 5% of older individuals who did not experience side effects


  random_older=randint(65,100)
  train_samples.append(random_older)
  train_labels.append(0)

# 95% of younger individuals who did not experience side effects

for i in range(1000):
  random_younger=randint(13,64)
  train_samples.append(random_younger)
  train_labels.append(0)

# 95% of older individuals who experienced side effects


  random_older=randint(65,100)
  train_samples.append(random_older)
  train_labels.append(1)


In [7]:
print(len(train_samples))

2100


In [8]:
print(len(train_labels))

2100


In [9]:
train_labels=np.array(train_labels)
train_samples=np.array(train_samples)
train_labels,train_samples=shuffle(train_labels,train_samples)

In [10]:
scaler=MinMaxScaler(feature_range=(0,1))
scaled_train_samples=scaler.fit_transform(train_samples.reshape(-1,1))
scaled_train_samples[0:5]

array([[0.42528736],
       [0.72413793],
       [0.68965517],
       [0.93103448],
       [0.49425287]])

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [12]:
model=Sequential([Dense(units=16,input_shape=(1,),activation='relu'),Dense(units=32,activation='relu'),Dense(units=2,activation='softmax')])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer=Adam(learning_rate=0.0001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [15]:
model.fit(x=scaled_train_samples,y=train_labels,validation_split=0.1,batch_size=10,shuffle=True,epochs=30,verbose=2)

Train on 1890 samples, validate on 210 samples
Epoch 1/30
1890/1890 - 1s - loss: 0.6900 - accuracy: 0.5905 - val_loss: 0.6805 - val_accuracy: 0.5619
Epoch 2/30
1890/1890 - 0s - loss: 0.6681 - accuracy: 0.6222 - val_loss: 0.6607 - val_accuracy: 0.6143
Epoch 3/30
1890/1890 - 0s - loss: 0.6467 - accuracy: 0.6667 - val_loss: 0.6396 - val_accuracy: 0.6905
Epoch 4/30
1890/1890 - 0s - loss: 0.6252 - accuracy: 0.7127 - val_loss: 0.6193 - val_accuracy: 0.7381
Epoch 5/30
1890/1890 - 0s - loss: 0.6051 - accuracy: 0.7423 - val_loss: 0.5991 - val_accuracy: 0.7619
Epoch 6/30
1890/1890 - 0s - loss: 0.5843 - accuracy: 0.7720 - val_loss: 0.5773 - val_accuracy: 0.7952
Epoch 7/30
1890/1890 - 0s - loss: 0.5628 - accuracy: 0.7942 - val_loss: 0.5548 - val_accuracy: 0.8000
Epoch 8/30
1890/1890 - 0s - loss: 0.5407 - accuracy: 0.8127 - val_loss: 0.5317 - val_accuracy: 0.8048
Epoch 9/30
1890/1890 - 0s - loss: 0.5185 - accuracy: 0.8254 - val_loss: 0.5084 - val_accuracy: 0.8143
Epoch 10/30
1890/1890 - 0s - loss: 

In [16]:
test_labels=[]
test_samples=[]

In [17]:
# 5% of younger individuals who experienced side effects
for i in range(50):
  random_younger=randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(1)

# 5% of older individuals who did not experience side effects


  random_older=randint(65,100)
  test_samples.append(random_older)
  test_labels.append(0)

# 95% of younger individuals who did not experience side effects

for i in range(200):
  random_younger=randint(13,64)
  test_samples.append(random_younger)
  test_labels.append(0)

# 95% of older individuals who experienced side effects


  random_older=randint(65,100)
  test_samples.append(random_older)
  test_labels.append(1)


In [18]:
scaler=MinMaxScaler(feature_range=(0,1))

In [19]:
test_labels=np.array(test_labels)
test_samples=np.array(test_samples)
test_labels,test_samples=shuffle(test_labels,test_samples)

In [20]:
scaled_test_samples=scaler.fit_transform(test_samples.reshape(-1,1))
scaled_test_samples[0:5]

array([[0.04597701],
       [0.68965517],
       [0.62068966],
       [0.91954023],
       [0.20689655]])

In [21]:
len(scaled_test_samples)

500

In [22]:
# Predict the label for test sample using the model
predictions=model.predict(x=scaled_test_samples,batch_size=10,verbose=0)

In [23]:
print(predictions[:5])

[[0.9432783  0.05672172]
 [0.22466871 0.7753313 ]
 [0.35363582 0.64636415]
 [0.05012684 0.94987315]
 [0.9448121  0.05518784]]


In [24]:
rounded_predictions=np.argmax(predictions,axis=-1)
rounded_predictions[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix

In [26]:
cm=confusion_matrix(y_true=test_labels,y_pred=rounded_predictions)

In [27]:
print(cm)

[[186  64]
 [ 48 202]]
